In [42]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [43]:
from sklearn import datasets
data = datasets.load_iris()

In [44]:
type(data)
print(data)

{'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]), 'DESCR': 'Iris Plants Database\n====================\n\nNotes\n-----\nData Set Characteristics:\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-

In [45]:
iris_df = pd.DataFrame(data.data,columns=data.feature_names)
iris_df['target'] = pd.Series(data.target)
iris_df.tail()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
145       2  
146       2  
147       2  
148       2  
149       2

In [46]:
new_iris = pd.DataFrame(data.data,columns=data.feature_names)
new_iris.head()
y = pd.DataFrame(data.target)
y.head()

0
0  0
1  0
2  0
3  0
4  0

In [68]:
from sklearn.cross_validation import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(new_iris,y,test_size=1/3,random_state=0)

In [69]:
#Multinomial naive bayes on original dataset
from sklearn.naive_bayes import GaussianNB
nb1 = GaussianNB()
nb1.fit(X_train,Y_train)

D:\Anaconda\envs\tensorflow\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB(priors=None)

In [70]:
ypred = nb1.predict(X_test)
ypred

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 1, 1, 1, 2, 0, 2, 0,
       0, 1, 2, 2, 1, 2])

In [71]:
Y_test

0
114  2
62   1
33   0
107  2
7    0
100  2
40   0
86   1
76   1
71   1
134  2
51   1
73   1
54   1
63   1
37   0
78   1
90   1
45   0
16   0
121  2
66   1
24   0
8    0
126  2
22   0
44   0
97   1
93   1
26   0
137  2
84   1
27   0
127  2
132  2
59   1
18   0
83   1
61   1
92   1
112  2
2    0
141  2
43   0
10   0
60   1
116  2
144  2
119  2
108  2

In [72]:
from sklearn.metrics import accuracy_score
print("Accuracy score is {0}".format(accuracy_score(Y_test,ypred)*100))

Accuracy score is 96.0


In [73]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(Y_test,ypred))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        16
          1       0.90      1.00      0.95        19
          2       1.00      0.87      0.93        15

avg / total       0.96      0.96      0.96        50



In [74]:
print(confusion_matrix(Y_test,ypred))

[[16  0  0]
 [ 0 19  0]
 [ 0  2 13]]


In [15]:
third_iris = iris_df.iloc[:,:2]
third_iris.head()


sepal length (cm)  sepal width (cm)
0                5.1               3.5
1                4.9               3.0
2                4.7               3.2
3                4.6               3.1
4                5.0               3.6

In [80]:
X_train1,X_test1,Y_train1,Y_test1 = train_test_split(third_iris,y,test_size=1/3,random_state=0)


In [81]:
#bernoulli - boolean features
#from sklearn.naive_bayes import BernoulliNB
nb2 = GaussianNB()
nb2.fit(X_train1,Y_train1)


D:\Anaconda\envs\tensorflow\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB(priors=None)

In [82]:
ypred1 = nb2.predict(X_test1)
ypred1

array([1, 1, 0, 2, 0, 2, 0, 2, 2, 1, 1, 2, 1, 2, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 2, 1, 0, 1, 1, 1, 0, 1, 1, 1, 2, 0, 2, 0,
       0, 1, 2, 2, 1, 2])

In [83]:
Y_test1

0
114  2
62   1
33   0
107  2
7    0
100  2
40   0
86   1
76   1
71   1
134  2
51   1
73   1
54   1
63   1
37   0
78   1
90   1
45   0
16   0
121  2
66   1
24   0
8    0
126  2
22   0
44   0
97   1
93   1
26   0
137  2
84   1
27   0
127  2
132  2
59   1
18   0
83   1
61   1
92   1
112  2
2    0
141  2
43   0
10   0
60   1
116  2
144  2
119  2
108  2

In [84]:
print("Accuracy score is {0}".format(accuracy_score(Y_test1,ypred1)*100))

Accuracy score is 78.0


In [85]:
print(classification_report(Y_test1,ypred1))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        16
          1       0.68      0.79      0.73        19
          2       0.67      0.53      0.59        15

avg / total       0.78      0.78      0.78        50



In [86]:
print(confusion_matrix(Y_test1,ypred1))

[[16  0  0]
 [ 0 15  4]
 [ 0  7  8]]
